# Template docker-push

# This template allows you to build and push your docker image to a Docker Hub account.
# The workflow allows running tests, code linting and security scans on feature branches (as well as master).
# The docker image will be validated and pushed to the docker registry after the code is merged to master.

# Prerequisites: $DOCKERHUB_USER, $DOCKERHUB_PWD setup as deployment variables

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            script:
              - docker build . --file Dockerfile --tag rainfall:latest
            services:
              - docker
            caches:
              - docker
        - step:
            name: Lint the Dockerfile
            image: hadolint/hadolint:latest-debian
            script:
              - hadolint Dockerfile
  branches:
    main:
      - step:
          name: Build and Test
          script:
            - docker build . --file Dockerfile --tag rainfall
            - docker save ${IMAGE_NAME} --output "rainfall.tar"
          services:
            - docker
          caches:
            - docker
          artifacts:
            - "*.tar"
      - step:
          name: Deploy to Production
          deployment: Production
          script:
            - echo ${DOCKERHUB_PWD} | docker login --username "$DOCKERHUB_USER" --password-stdin
            - docker load --input "rainfall.tar"
            - IMAGE_NAME="rainfall"
            - IMAGE="proslabunicam/rainfall"
            - VERSION="prod-0.1.${BITBUCKET_BUILD_NUMBER}"
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
            - docker push "${IMAGE}:${VERSION}"
          services:
            - docker
