image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            script:
              - IMAGE_NAME="rainfall"
              - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            services:
              - docker
            caches:
              - docker
        - step:
            name: Lint the Dockerfile
            image: hadolint/hadolint:latest-debian
            script:
              - hadolint Dockerfile
  branches:
    main:
      - parallel:
          - step:
              name: Build Rainfall webapp image
              script:
                - IMAGE_NAME="rainfall"
                - docker build . --file Dockerfile --tag ${IMAGE_NAME}
                - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
              services:
                - docker
              caches:
                - docker
              artifacts:
                - "*.tar"
          - step:
              name: Build Rainfall worker Image
              script:
                - IMAGE_NAME="rainfall_worker"
                - export DOCKER_BUILDKIT=1
                - docker build . --file Dockerfile.worker --tag ${IMAGE_NAME} --build-arg SSH_KEY="${SSH_KEY}"
                - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
              services:
                - docker
              caches:
                - docker
              artifacts:
                - "*_worker.tar"
      - step:
          name: Deploy to Production
          deployment: Production
          script:
            - echo ${DOCKERHUB_PWD} | docker login --username "$DOCKERHUB_USER" --password-stdin
            # Load and push the webapp image
            - docker load --input "rainfall.tar"
            - IMAGE_NAME="rainfall"
            - IMAGE="proslabunicam/rainfall"
            - VERSION="prod-0.1.${BITBUCKET_BUILD_NUMBER}"
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
            - docker push "${IMAGE}:${VERSION}"
            # Load and push the worker image
            - docker load --input "rainfall_worker.tar"
            - WORKER_IMAGE_NAME="rainfall_worker"
            - WORKER_IMAGE="proslabunicam/rainfall_worker"
            - WORKER_VERSION="prod-0.1.${BITBUCKET_BUILD_NUMBER}"
            - docker tag "${WORKER_IMAGE_NAME}" "${WORKER_IMAGE}:${WORKER_VERSION}"
            - docker push "${WORKER_IMAGE}:${WORKER_VERSION}"
          services:
            - docker

definitions:
  caches:
    docker: /var/lib/docker