version: '3'

services:

  webapp:
    build: .
    image: rainfall
    restart: always
    ports:
      - 5000:5000
    environment:
      - MODE=PROD
      - PORT=5000
      - SERVER_ADDR=0.0.0.0
      - RAIN_REPOSITORY_URL=git+ssh://git@bitbucket.org/proslabteam/rain_unicam@main#egg=rain
      - RAIN_STRUCTURE_URL=https://firebasestorage.googleapis.com/v0/b/rainfall-e8e57.appspot.com/o/rain_structure.json?alt=media
      - MONGODB_URL=mongodb://mongo:27017/
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      # - SECRET_KEY=

      # Uncomment during development
      # - MODE=DEBUG
      # - RAIN_REPOSITORY_URL=git+ssh://git@bitbucket.org/proslabteam/rain_unicam@dev#egg=rain

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u mongo -p mongo --quiet) -eq 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo-init:
    image: mongo
    restart: on-failure:20
    depends_on:
      - mongo
    command: >
      mongosh --host mongo:27017 --eval 
      '
        var cfg = {
          "_id": "rs0",
          "version": 1,
          "members": [
            {
              "_id": 0,
              "host": "mongo:27017",
              "priority": 2
            }
          ]
        };
        rs.initiate(cfg);
      '

  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  worker:
    build: .
    image: rainfall_worker
    command: celery -A simple_backend.service.execution_service.celery worker --loglevel=info
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/