services:
  webapp:
    image: proslabunicam/rainfall
    restart: always
    volumes:
      - data-volume:/tmp/data
    ports:
      - 5000:5000
    environment:
      - MODE=PROD
      - PORT=5000
      - SERVER_ADDR=0.0.0.0
      - RAIN_REPOSITORY_URL=git+ssh://git@bitbucket.org/proslabteam/rain_unicam@main#egg=rain
      - RAIN_STRUCTURE_URL=https://firebasestorage.googleapis.com/v0/b/rainfall-e8e57.appspot.com/o/rain_structure.json?alt=media
      - MONGODB_URL=mongodb://mongo:27017/?directConnection=true
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]

  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  worker1:
    image: proslabunicam/rainfall_worker
    command: celery -A simple_backend.service.execution_service.celery worker --loglevel=info
    restart: always
    volumes:
      - data-volume:/tmp/data
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  worker2:
    image: proslabunicam/rainfall_worker
    command: celery -A simple_backend.service.execution_service.celery worker --loglevel=info
    restart: always
    volumes:
      - data-volume:/tmp/data
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      
volumes:
  data-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /tmp/data