version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      [
        net
      ]
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]

  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      [
        net
      ]

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1